spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  show-sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL:
#          DEBUG

#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.jpa.show-sql: true
